# Generated by Django 5.2.11 on 2026-02-16 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_date'], 'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
    ]
